# Generated by Django 6.0.4 on 2026-04-26 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrandDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('phones', models.JSONField(blank=True, default=list)),
                ('emails', models.JSONField(blank=True, default=list)),
                ('facebook', models.JSONField(blank=True, default=list, null=True)),
                ('instagram', models.JSONField(blank=True, default=list, null=True)),
                ('twitter', models.JSONField(blank=True, default=list, null=True)),
                ('linkedin', models.JSONField(blank=True, default=list, null=True)),
                ('youtube', models.JSONField(blank=True, default=list, null=True)),
                ('tiktok', models.JSONField(blank=True, default=list, null=True)),
                ('dealers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywords_scraping.carbrand')),
            ],
        ),
    ]
