# Generated by Django 6.0.4 on 2026-04-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_scraping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbrand',
            name='socials',
        ),
        migrations.AddField(
            model_name='carbrand',
            name='facebook',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='carbrand',
            name='instagram',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='carbrand',
            name='linkedin',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='carbrand',
            name='tiktok',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='carbrand',
            name='twitter',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='carbrand',
            name='youtube',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
