# Generated by Django 6.0.4 on 2026-05-10 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dealers',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dealers',
            name='brand_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dealers', to='keywords_scraping.branddetails'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dealers',
            unique_together={('brand_detail', 'name', 'address')},
        ),
    ]
