# Generated by Django 6.0.4 on 2026-04-26 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branddetails',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='keywords_scraping.carbrand'),
        ),
    ]
