# Generated by Django 6.0.4 on 2026-04-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_scraping', '0002_remove_carbrand_socials_carbrand_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='facebook',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='instagram',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='linkedin',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='tiktok',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='twitter',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='youtube',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
