# Generated by Django 6.0.4 on 2026-04-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_scraping', '0002_alter_branddetails_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branddetails',
            name='logo',
        ),
    ]
