# Generated by Django 6.0.4 on 2026-05-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_scraping', '0002_alter_dealers_unique_together_dealers_brand_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealers',
            name='brand',
        ),
    ]
