# Generated by Django 6.0.4 on 2026-04-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_scraping', '0003_alter_carbrand_facebook_alter_carbrand_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='keyword',
            field=models.CharField(max_length=500),
        ),
    ]
