# Generated by Django 6.0.4 on 2026-05-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_scraping', '0003_remove_dealers_brand'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dealers',
            unique_together=set(),
        ),
    ]
