# Generated by Django 6.0.4 on 2026-04-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_scraping', '0004_alter_carbrand_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='dealers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
